name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20.x'
  PNPM_VERSION: '8.15.1'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          
      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile || pnpm install --no-frozen-lockfile
          else
            pnpm install
          fi
          
      - name: Generate React Router Types
        run: pnpm remix-router types
        
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
          
      - name: Run Biome
        run: pnpm biome ci .
        
      - name: Type Check
        run: pnpm tsc --noEmit

  test:
    name: Test
    needs: validate
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          
      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile || pnpm install --no-frozen-lockfile
          else
            pnpm install
          fi

      - name: Generate React Router Types
        run: pnpm remix-router types
        
      - name: Run tests
        run: pnpm test -- --coverage
        
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          retention-days: 14
          
  build:
    name: Build
    needs: [validate, test]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          
      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile || pnpm install --no-frozen-lockfile
          else
            pnpm install
          fi

      - name: Generate React Router Types
        run: pnpm remix-router types
        
      - name: Build
        run: pnpm build
        
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 14

  status-check:
    name: Status Check
    needs: [validate, test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        run: echo "All checks passed successfully!"